Repository MasterCruelty/mastercruelty.github.io, pull requests merged in 2021-11, with the labels that each got.

#1 :wrench: Update page
  Sezioni/progetti.html
  src/atmshitposting.html
  src/home.html
  src/logo.jpg
  src/progetti.html
Labels: enhancement, low priority

#3 Fix broken links
  src/atmshitposting.html
Labels: bug, fix

#4 💄 css style
  src/atmshitposting.html
  src/style.css
Labels: refactor
